# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BatteryData.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x42\x61tteryData.proto\"9\n\x07\x62\x61ttery\x12\x0f\n\x07voltage\x18\x01 \x01(\x02\x12\x1d\n\x05state\x18\x02 \x01(\x0e\x32\x0e.battery_state*\xf9\x01\n\rbattery_state\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0c\n\x08\x43HARGING\x10\x01\x12\x0f\n\x0b\x44ISCHARGING\x10\x02\x12\x0b\n\x07\x43HARGED\x10\x03\x12\x0e\n\nDISCHARGED\x10\x04\x12\x0f\n\x0bOVERCHARGED\x10\x05\x12\x12\n\x0eOVERDISCHARGED\x10\x06\x12\x13\n\x0fOVERTEMPERATURE\x10\x07\x12\x0f\n\x0bOVERCURRENT\x10\x08\x12\x0f\n\x0bOVERVOLTAGE\x10\t\x12\x10\n\x0cUNDERVOLTAGE\x10\n\x12\x14\n\x10UNDERTEMPERATURE\x10\x0b\x12\x10\n\x0cUNDERCURRENT\x10\x0c\x12\t\n\x05\x46\x41ULT\x10\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BatteryData_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BATTERY_STATE']._serialized_start=81
  _globals['_BATTERY_STATE']._serialized_end=330
  _globals['_BATTERY']._serialized_start=21
  _globals['_BATTERY']._serialized_end=78
# @@protoc_insertion_point(module_scope)
