# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shadow.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cshadow.proto\"I\n\x06Shadow\x12\x1f\n\nsshSetting\x18\x01 \x01(\x0e\x32\x0b.SSH_ENABLE\x12\x0f\n\x07\x62\x61ttery\x18\x02 \x01(\x02\x12\r\n\x05inUse\x18\x03 \x01(\x08*%\n\nSSH_ENABLE\x12\x0b\n\x07\x44ISABLE\x10\x00\x12\n\n\x06\x45NABLE\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shadow_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SSH_ENABLE']._serialized_start=91
  _globals['_SSH_ENABLE']._serialized_end=128
  _globals['_SHADOW']._serialized_start=16
  _globals['_SHADOW']._serialized_end=89
# @@protoc_insertion_point(module_scope)
